installCRDs: true

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${role_arn}

securityContext:
  fsGroup: 1001

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/capacityType
          operator: In
          values:
            - ON_DEMAND

cainjector:
  enabled: true
  replicaCount: 1

  extraArgs:
    - --leader-elect=false
