# Environment variables to set on deployment pod
env:
  AWS_REGION: ${region}
  AWS_DEFAULT_REGION: ${region}
  POLLER_INTERVAL_MILLISECONDS: 30000
  # trace, debug, info, warn, error, fatal
  LOG_LEVEL: warn
  LOG_MESSAGE_KEY: 'msg'
  METRICS_PORT: 3001

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${role_arn}

securityContext:
  # Required for use of IRSA, see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
  fsGroup: 1000
