imageTag: "7.8.0"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - ${domain_name}
#  tls:
#  - hosts: 
#    - ${domain_name}

apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      # ssl:
      #   enabled: true
      #   certificate: /usr/share/apm-server/config/certs/tls.crt
      #   key: /usr/share/apm-server/config/certs/tls.key
    queue: {}
    output.elasticsearch:
      username: '$${ELASTICSEARCH_USERNAME}'
      password: '$${ELASTICSEARCH_PASSWORD}'
      protocol: https
      hosts: ["elasticsearch-master:9200"]
      ssl.verification_mode: none

secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/apm-server/config/certs

extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/lifecycle
          operator: NotIn
          values:
            - spot
