{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "teamcity.fullname" . }}-agent
  labels:
    app: {{ template "teamcity.name" . }}-agent
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}-agent
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}-agent
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
            - name: SERVER_URL
              value: "http://{{ template "teamcity.fullname" . }}:8111"
          resources:
{{ toYaml .Values.agent.resources | indent 12 }}
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
    {{- with .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.agent.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.agent.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}